@startuml wehkammp2punt0
set namespaceSeparator ::

class "wehkammp2punt0::models::product.dart::Product" {
  +String id
  +String title
  +String description
  +double price
  +String imageUrl
  +bool isFavorite
}

class "wehkammp2punt0::main.dart::MyApp" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "wehkammp2punt0::main.dart::MyApp"

class "wehkammp2punt0::components::hero_animation.dart::HeroAnimation" {
  +String imageurL
  +String description
  +double price
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "wehkammp2punt0::components::hero_animation.dart::HeroAnimation"

class "wehkammp2punt0::components::product_item.dart::ProductItem" {
  +String id
  +String title
  +String imageUrl
  +String description
  +double price
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "wehkammp2punt0::components::product_item.dart::ProductItem"

class "wehkammp2punt0::components::photo_hero.dart::PhotoHero" {
  +String photo
  +void Function() onTap
  +double width
  +Widget build()
}

"wehkammp2punt0::components::photo_hero.dart::PhotoHero" o-- "dart::ui::void Function()"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "wehkammp2punt0::components::photo_hero.dart::PhotoHero"

class "wehkammp2punt0::pages::products_overview_page.dart::ProductOverviewPage" {
  +State<ProductOverviewPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "wehkammp2punt0::pages::products_overview_page.dart::ProductOverviewPage"

class "wehkammp2punt0::pages::products_overview_page.dart::_ProductOverviewPageState" {
  +List<Product> loadedProducts
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "wehkammp2punt0::pages::products_overview_page.dart::_ProductOverviewPageState"


@enduml