@startuml wehkammp2punt0

class "Product" {
  +String id
  +String title
  +String description
  +double price
  +String imageUrl
  +bool isFavorite
}

class "HeroAnimation" {
  +String imageurL
  +String description
  +double price
}

class "ProductItem" {
  +String id
  +String title
  +String imageUrl
  +String description
  +double price
}

class "PhotoHero" {
  +String photo
  +void Function() onTap
  +double width
}

class "ProductOverviewPage" {
  +State<ProductOverviewPage> createState()
}

class "_ProductOverviewPageState" {
  +List<Product> loadedProducts
}

@enduml